{% set name = "json5" %}
{% set version = "0.9.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/json5-{{ version }}.tar.gz
  sha256: 717d99d657fa71b7094877b1d921b1cce40ab444389f6d770302563bb7dfd9ae

build:
  entry_points:
    - pyjson5=json5.tool:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - json5
  commands:
    - pip check
    - pyjson5 --help
  requires:
    - pip

about:
  home: https://github.com/dpranke/pyjson5
  summary: A Python implementation of the JSON5 data format.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - ian-r-rose
